name: CI
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    if: ${{ github.event_name == 'push' && !startsWith(github.event.ref, 'refs/tags/') && contains(github.event.head_commit.message, '[build skip]') == false }}
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ./.gradle/loom-caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Get short commit sha
        id: get_short_sha
        run: |
          short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      - name: Get commit count
        id: get_commit_count
        run: |
          commit_count=$(git log | grep -e 'commit [a-zA-Z0-9]*' | wc -l)
          echo "commit_count=$commit_count" >> $GITHUB_OUTPUT

      - name: Read Properties mod info
        id: mod_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_name mod_version'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish Maven with Gradle
        env:
          BUILD_TYPE: "BETA"
        run: ./gradlew build --stacktrace

      - name: Upload assets to GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.mod_info.outputs.mod_name }} ${{ steps.mod_info.outputs.mod_version }}.${{ steps.get_commit_count.outputs.commit_count }}+${{ steps.get_short_sha.outputs.short_sha }}"
          path: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/build/tmp/submods/META-INF/jars/*.jar

      - name: Create Github release
        if: contains(github.event.head_commit.message, '[publish skip]') == false && contains(github.event.ref, 'refs/heads/exp') == false
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/build/tmp/submods/META-INF/jars/*.jar
          name: "[CI#${{ github.run_number }}]${{ steps.mod_info.outputs.mod_name }} ${{ steps.mod_info.outputs.mod_version }}.${{ steps.get_commit_count.outputs.commit_count }}+${{ steps.get_short_sha.outputs.short_sha }}"
          tag_name: "${{ github.ref_name }}.${{ github.run_number }}"
          target_commitish: ${{ github.event.ref }}
          generate_release_notes: true
